# Generated by Django 2.2.4 on 2020-05-19 10:16
import phonenumbers
from django.db import migrations


def fill_correct_phone_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        try:
            phone_number = phonenumbers.parse(flat.owners_phonenumber)
            flat.owner_phone_pure = phonenumbers.format_number(phone_number,
                                                               phonenumbers.PhoneNumberFormat.INTERNATIONAL)
        except Exception:
           pass
        
        flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0008_auto_20200519_1308'),
    ]
    
    operations = [
        migrations.RunPython(fill_correct_phone_number)
    ]
