# Generated by Django 2.2.4 on 2020-05-19 13:25

from django.db import migrations
import phonenumbers


def fill_correct_phone_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        try:
            phone_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
            flat.owner_phone_pure = phonenumbers.format_number(phone_number,
                                                           phonenumbers.PhoneNumberFormat.INTERNATIONAL)
        except phonenumbers.phonenumberutil.NumberParseException:
            flat.owner_phone_pure = None
        flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0009_auto_20200519_1316'),
    ]
    
    operations = [
        migrations.RunPython(fill_correct_phone_number)
    ]
