# Generated by Django 2.2.4 on 2020-05-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_remove_flat_owners_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200, verbose_name='ФИО владельца')),
                ('owner_number', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Номер владельца')),
                ('owner_number_norm', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Нормализованный номер владельца')),
            ],
        ),
    ]
