# Generated by Django 2.2.4 on 2020-05-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='owner',
            new_name='owner_old',
        ),
        migrations.AddField(
            model_name='owner',
            name='ownership_apart',
            field=models.ManyToManyField(to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
