# Generated by Django 2.2.4 on 2020-05-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20200520_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='ownership_apart',
            field=models.ManyToManyField(blank=True, null=True, to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
