# Generated by Django 2.2.4 on 2020-05-20 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20200520_1706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
