# Generated by Django 2.2.4 on 2020-05-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20200520_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner_number',
            field=models.CharField(db_index=True, max_length=10, null=True, verbose_name='Номер владельца'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_number_norm',
            field=models.CharField(db_index=True, max_length=10, null=True, verbose_name='Нормализованный номер владельца'),
        ),
    ]
