# Generated by Django 2.2.4 on 2020-05-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_delete_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200, verbose_name='ФИО владельца')),
                ('owner_number', models.CharField(db_index=True, max_length=10, null=True, verbose_name='Номер владельца')),
                ('owner_number_norm', models.CharField(db_index=True, max_length=10, null=True, verbose_name='Нормализованный номер владельца')),
                ('ownership_apart', models.ManyToManyField(blank=True, null=True, to='property.Flat', verbose_name='Квартиры в собственности')),
            ],
        ),
    ]
