# Generated by Django 2.2.4 on 2020-05-20 14:19

from django.db import migrations


def switch_owner_model(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        flat_phonenumber = flat.owners_phonenumber
        flat_pure_phonenumber = flat.owner_phone_pure
        Owner.objects.update_or_create(owner=flat.owner_old, defaults={
            'owner_number': flat_phonenumber,
            'owner_number_norm': flat_pure_phonenumber,
        })


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0018_owner'),
    ]
    
    operations = [
        migrations.RunPython(switch_owner_model)
    ]
