# Generated by Django 2.2.4 on 2020-05-21 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_auto_20200520_1719'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
