# Generated by Django 2.2.4 on 2020-05-21 06:01

from django.db import migrations


def switch_owner_model(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            owner=flat.owner_old,
            owner_number=flat.owners_phonenumber,
            owner_number_norm=flat.owner_phone_pure)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0021_owner'),
    ]
    
    operations = [
        migrations.RunPython(switch_owner_model)
    ]
