# Generated by Django 2.2.4 on 2020-05-21 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_auto_20200521_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='owner_old',
            new_name='flats_owner',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='ownership_apart',
            new_name='flats',
        ),
    ]
