# Generated by Django 2.2.4 on 2020-05-21 10:09

from django.db import migrations


def fill_owner_flat(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for owner in Owner.objects.all():
        owner_name = owner.owner
        flat = Flat.objects.filter(flat_owner=owner_name)
        owner.flats.set(flat)
        owner.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0029_auto_20200521_1302'),
    ]
    
    operations = [
        migrations.RunPython(fill_owner_flat)
    ]
