# Generated by Django 2.2.4 on 2020-05-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0031_auto_20200527_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claim_text',
            field=models.TextField(blank=True, verbose_name='Текст жалобы'),
        ),
    ]
