# Generated by Django 2.2.4 on 2020-05-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0032_auto_20200527_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner_number',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Номер владельца'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_number_norm',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Нормализованный номер владельца'),
        ),
    ]
