# Generated by Django 2.2.4 on 2020-06-01 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0036_auto_20200527_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='customer',
            new_name='website_visitor',
        ),
    ]
