# Generated by Django 2.2.4 on 2020-06-01 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0038_auto_20200601_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='rooms_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_rooms', to='property.Flat', verbose_name='Номер комнаты'),
        ),
    ]
